notifications:
  recipients:
    - gauche-travis@lists.sourceforge.net
language: c
addons:
  apt:
    packages: &apt_packages
      - libgdbm-dev
      - zlib1g-dev
      - texinfo
  homebrew:
    packages:
      - gdbm
      - zlib
      - texinfo
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
before_install:
  - eval "${MATRIX_EVAL}"
  # sudo cannot find clang, so We install Gauche under $HOME without sudo
  # https://github.com/travis-ci/travis-ci/issues/3088
  - curl -o get-gauche.sh -f https://raw.githubusercontent.com/shirok/get-gauche/master/get-gauche.sh && chmod +x get-gauche.sh && ./get-gauche.sh --auto --home && ./DIST gen
script:
  - ./configure && make -j4 && make check && cd doc && make
